name: dbclientapp
description: A database client app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+7

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.4.0+1
  path: ^1.7.0
  flutter_speed_dial: ^2.1.1
  path_provider: ^1.6.27
  csv: ^4.1.0
  esys_flutter_share: ^1.0.2
  flutter_local_notifications: ^4.0.0
  open_file: ^3.0.3
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  # firebase_crashlytics: ^0.4.0+1
  flutter_datetime_picker: ^1.5.0
  intl_phone_number_input: ^0.6.0
  pin_code_fields: ^6.1.0
  sms_autofill: ^1.3.1
  devicelocale: ^0.3.3
  flushbar: ^1.10.4
  emojis: ^0.9.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  mobx_codegen: ^1.1.2
  moor_generator: ^3.4.1
  build_runner: ^1.11.1
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/ic_android.png"
  image_path_ios: "assets/icon/ic_ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: IconsForMyApp
      fonts:
        - asset: assets/font_icons/IconsForMyApp.ttf
    - family: Balsamiq Sans
      fonts:
        - asset: assets/fonts/Balsamiq_Sans/BalsamiqSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Balsamiq_Sans/BalsamiqSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Balsamiq_Sans/BalsamiqSans-Italic.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
